name: Deploy Backend to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: protinf-e061fd7b2275
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          procfile: "web: gunicorn app:app --bind 0.0.0.0:$PORT --workers 4 --timeout 120"
